<?php
namespace Kitodo\Dlf\ViewHelpers;

use TYPO3\CMS\Extbase\Utility\DebuggerUtility;
use TYPO3Fluid\Fluid\Core\Rendering\RenderingContextInterface;
use TYPO3Fluid\Fluid\Core\ViewHelper\Traits\CompileWithRenderStatic;
use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper;


class TimecodeViewHelper extends AbstractViewHelper
{

    use CompileWithRenderStatic;

    public function initializeArguments()
    {
        parent::initializeArguments(); // TODO: Change the autogenerated stub
        $this->registerArgument('timecode', 'string', 'the timecode', true);
    }

    /**
     * Return result of calculation
     * @param array $arguments
     * @param \Closure $renderChildrenClosure
     * @param RenderingContextInterface $renderingContext
     * @return string
     */
    public static function renderStatic(
        array $arguments,
        \Closure $renderChildrenClosure,
        RenderingContextInterface $renderingContext
    )
    {

        $str_time = $arguments['timecode'];

        $str_time = preg_replace("/^([\d]{1,2})\:([\d]{2})$/", "00:$1:$2", $str_time);

        sscanf($str_time, "%d:%d:%d:%d", $hours, $minutes, $seconds, $milliseconds);

        $time_seconds = $hours * 3600 + $minutes * 60 + $seconds + ($milliseconds != 0 ? 1 / $milliseconds : 0);

        return (string)$time_seconds;
    }
}
